bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

boutique_ado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('profiles.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('int:<product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),

]
# above, 'int: ' is necessary because otherwise when navigating to 'add/', this can be considered the id. like id=add

checkout/models.py
import uuid  # used to generate the order number

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


# Create your models here.
# Class Order = model
class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    # below, set_null will allow us to keep the orders even if profile is deleted
    # Blank= true, this way, users that are not loggin can still place orders
    # related_name = orders, to allow dot walking like user.user_profile.orders. ...
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    # below three values will be calculated on model method
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    # above fields postcode and county is not required cus not all countries has it.
    # auto_now_add = add date automaticaly.
    # underscore method by convention means private method. Only used in this method
    # below two fields are meant to avoid confusion with original order and new order.
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False, blank=False, default='')
    # add above 2 fields to checkout/admin.py

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line items is added,
        accounting for delivery costs
        """
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        # above: 'or 0' is to prevent a value null and make it 0 to 
        # ...avoid errors.
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    # overwritting default save method
    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


# this is a model
class OrderLineItem(models.Model):
    # below foreignkey will allow dotwalking
    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True, blank=True)  # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, editable=False)

    # overwritting default save method
    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
  
    class Meta:
        verbose_name_plural = 'Categories'
# this is to correct the plural
# conversion of 'Category(...)'. See the admin page

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)
    # null and blank true allow the variable to be optional

    # creating a string method, with data model = self /what does it do?
    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


# Model for the product
class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    # when changing this part above, it changes the structure of the model.
    # ... Therefore needs to run migrations
    # (test) python3 manage.py makemigrations --dry-run
    # (run migration) python3 manage.py makemigrations
    # (it shows the migrations that will be run):
    # ... python3 manage.py migrate --plan

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category


class ProductForm(forms.ModelForm):
    # meta defines the model and fields we want to include
    class Meta:
        model = Product
        # use dunder __all__ to select all fields from the model
        fields = '__all__'

    # add image field from the customized widget
    image = forms.ImageField(label='Image', required=False, widget=CustomClearableFileInput)

    # override __init__ method to make a changes on some fields
    def __init__(self, *args, **kwargs):
        # What *args allows you to do is take in more arguments than the number of formal arguments that you previously defined. With *args, any number of extra arguments can be tacked on to your current formal parameters (including zero extra arguments). https://www.geeksforgeeks.org/args-kwargs-python/
        super().__init__(*args, **kwargs)
        # above, kwarg is keyword = value
        # get all categories friendly names in to a tupple
        categories = Category.objects.all()
        # below is a short way to add items to a list
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        # using the friendly name instead of the ids for choices
        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
# Q = is important for searches, instead of returning resuts for where the terms or found in all fields, it returns if the term is found in either fields
from django.db.models import Q
from django.db.models.functions import Lower
from .models import Product, Category

from .forms import ProductForm

# Create your views here.


def all_products(request):
    """ A view to show all products, including sorting and search queries """

    products = Product.objects.all()
    # to avoid getting error for running the code without a search term
    query = None
    categories = None
    sort = None
    direction = None

# this if is for the "Clothing" menu item
    if request.GET:
        print('all_product function inside the request.GET if ---------***********-----------------**************------------')
        if 'sort' in request.GET:
            print('all_product function - inside the request.GET if sort in these ---------***********-----------------**************------------')
            sortkey = request.GET['sort']
            print(str(sortkey) + ' = value of sortkey in string format ---------***********-----------------**************------------')
            sort = sortkey
            print(sort + '= print sort app_product function ---------***********-----------------**************------------')

            #  to make sorting case insensitive, we have to create a temporary
            # ...field called lower.
            if sortkey == 'name':
                sortkey = 'lower_name'
                print(str(sortkey) + ' = under sort key = name ---------***********-----------------**************------------')
                products = products.annotate(lower_name=Lower('name'))
                print(products)
                print(lower_name)

            if sortkey == 'category':
                sortkey = 'category__name'  # double underline allow driling
                # ... into a model

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            # the below variable put all categories on a list splitted
            # ... via comma
            categories = request.GET['category'].split(',')
            # the below variable filter products based the category
            products = products.filter(category__name__in=categories)
            # the double underline above means grab category names with
            # ... category=categorynamefrom list above
            # below, variable contain a list of all categories . Since it is
            # ... an object, we can access the category fields from the template
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "You didn;t enter any search criteria!")
                return redirect(reverse('products'))

            queries = Q(
                name__icontains=query) | Q(description__icontains=query)
            # icontains = i means case insensitive
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual product details """
    print(product_id + '  = product_id ---------***********-----------------**************------------')
    product = get_object_or_404(Product, pk=product_id)
    print(product)

    context = {
        'product': product,
    }

    return render(request, 'products/product_detail.html', context)

def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        # the request.files is to get images
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request,
                           ('Failed to add product. '
                            'Please ensure the form is valid.'))
    else:
        # add an instance of a form
        form = ProductForm()
    print("product/views.py > add_product > form instance ---------***********-----------------**************------------")
    print(form)
    print(" end of form instance ---------***********-----------------**************------------")
    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)

def edit_product(request, product_id):
    """ Edit a product in the store """
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        print("edit_product -> product = ---------***********-----------------**************------------")
        print(product)
        print('product end')
        print("edit_product form = ---------***********-----------------**************------------")
        print(form)
        print('form end')

        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product. Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)

def delete_product(request, product_id):
    """ Delete a product from the store """
    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h5 class="text-muted">Add a Product</h5>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6">
            <!-- make sure to wrap everything inside of a form  -->
            <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">  <!-- enctype is necessary because there will be images in this form and without it, there could be problems -->
                {% csrf_token %}
                <!-- all this for to delete a label that is coming from crispy form. It says, if we are using the widget get rid of label 'image' -->
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                    <button class="btn btn-black rounded-0" type="submit">Add Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

<!--  message to let them now that the image has been changed -->
{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h5 class="text-muted">Edit a Product</h5>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2"
                enctype="multipart/form-data">
                {% csrf_token %}
                <!-- all this for to delete a label that is coming from crispy form. It says, if we are using the widget get rid of label 'image' -->
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                    <button class="btn btn-black rounded-0" type="submit">Update Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

<!--  message to let them now that the image has been changed -->
{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

<!-- the blocks page_header and block content is in the same order as the index.html under home, but it has no content in it -->

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
            <div class="image-container my-5">
                <!-- render product image -->
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="">
                    <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                </a>
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <div class="product-details-container mb-5 mt-md-5">
                <p class="mb-0">{{ product.name }}</p>
                <p class="lead mb-0 text-left font-weight-bold">${{ product.price }}</p>
                {% if product.category %}
                <p class="small mt-1 mb-0">
                    <a href="{% url 'products' %}?category={{ product.category.name }}" class="text-muted">
                        <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                    </a>
                </p>
                {% endif %}
                {% if product.rating %}
                <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                {% else %}
                <small class="text-muted">No Rating</small>
                {% endif %}
                <!-- If super user allow edit and delete -->
                {% if request.user.is_superuser %}
                <small class="ml-3">
                    <a href="{% url 'edit_product' product.id %}">Edit</a> |
                    <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                </small>
                {% endif %}
                <p class="mt-3">{{ product.description }}</p>

                <!-- Form for buying item -->
                <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST"> <!-- how a this html can call a view that is inside of other application???-->
                    {% csrf_token %}
                    <!-- this token is here because below is a form with post to take advantage of Django cross site request form forgery protection -->
                    
                    <!-- quantity section of the form -->
                    <div class="form-row">
                        
                        <!-- select size box -->
                        {% with product.has_sizes as s %}
                        {% if s %}
                        <div class="col-12">
                            <p><strong>Size:</strong></p>
                            <select class="form-control rounded-0 w-50" name="product_size" id='id_product_size'>
                                <option value="xs">XS</option>
                                <option value="s">S</option>
                                <option value="m" selected>M</option>
                                <option value="l">L</option>
                                <option value="xl">XL</option>
                            </select>
                        </div>
                        {% endif %}

                        <div class="col-12">
                            <p class="mt-3"><strong>Quantity:</strong></p>
                            <div class="form-group w-50">
                            
                                <!-- functionality to increase or decrease quantity -->
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <button class="decrement-qty btn btn-black rounded-0"
                                            data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-minus"></i>
                                            </span>
                                        </button>
                                    </div>
                                    <input class="form-control qty_input" type="number" name="quantity" value="1"
                                        min="1" max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                                    <div class="input-group-append">
                                        <button class="increment-qty btn btn-black rounded-0"
                                            data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-plus"></i>
                                            </span>
                                        </button>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <!-- keep shopping  and submit  button -->
                        <div class="col{% if s %}-12 mt-2{% endif %}">
                            <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 mt-5">
                                <span class="icon">
                                    <i class="fas fa-chevron-left"></i>
                                </span>
                                <span class="text-uppercase">Keep Shopping</span>
                            </a>
                            <input type="submit" class="btn btn-black rounded-0 text-uppercase mt-5" value="Add to Bag">
                        </div>
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        <!-- this functionality is good to take the user to the page he was previously at -->
                        {% endwith %}
                    </div>
                </form>



            </div>
        </div>
    </div>

</div>
{% endblock %}

<!-- this is part of what is needed to make the buttons on quantity to work -->
{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}  